# config/thin.yml
# like: thin start -a localhost -p 3000
# address: localhost
# port: 3000


# To specify multiple hosts and ports in Thin web server,
# you can use the -a and -p options with a comma-separated list of values.

# thin start -a localhost,192.168.0.100 -p 3000,4000

# In this example, Thin will listen on localhost at port 3000 and on 192.168.0.100 at port 4000. 
# You can add more host and port combinations as needed, separated by commas.

# You can also specify multiple hosts and ports in a Thin configuration file.
# Here's an example of how to specify two hosts and ports in a config/thin.yml file:

# config/thin.yml
address: localhost,192.168.0.100
port: "3000,4000"

#then => thin start -C config/thin.yml